
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SUMA = 11;
  public static final int MOSTRAR = 5;
  public static final int MULTIPLICACION = 13;
  public static final int VARIABLE = 4;
  public static final int EOF = 0;
  public static final int NUMERO = 10;
  public static final int LEER = 3;
  public static final int CIERROCOMENTARIO = 8;
  public static final int error = 1;
  public static final int PTOYCOMA = 2;
  public static final int ASIGNACION = 6;
  public static final int DIVISION = 14;
  public static final int ABROCOMENTARIO = 7;
  public static final int RESTA = 12;
  public static final int COMENTARIOLINEA = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PTOYCOMA",
  "LEER",
  "VARIABLE",
  "MOSTRAR",
  "ASIGNACION",
  "ABROCOMENTARIO",
  "CIERROCOMENTARIO",
  "COMENTARIOLINEA",
  "NUMERO",
  "SUMA",
  "RESTA",
  "MULTIPLICACION",
  "DIVISION"
  };
}

